# Writes OUT, a header with the source tree's git commit (and "-dirty" when
# tracked files differ from it), rewriting it only when that changes, so
# only the files that include it rebuild. Run at every build by the
# git_hash target (CMakeLists.txt).
execute_process(COMMAND git rev-parse --short HEAD WORKING_DIRECTORY ${SRC}
                OUTPUT_VARIABLE hash OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
execute_process(COMMAND git status --porcelain --untracked-files=no WORKING_DIRECTORY ${SRC}
                OUTPUT_VARIABLE dirty OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
if (NOT hash)
    set(hash "unknown")
endif()
if (dirty)
    set(hash "${hash}-dirty")
endif()
set(content "#pragma once\n// Generated by cmake/git_hash.cmake.\ninline constexpr const char* GIT_HASH = \"${hash}\";\n")
if (EXISTS ${OUT})
    file(READ ${OUT} old)
endif()
if (NOT "${old}" STREQUAL "${content}")
    file(WRITE ${OUT} "${content}")
endif()
